### ISSUE TITLE
API change?

### ISSUE THREAD

**Issue by DerekParks** [home-assistant/home-assistant-cli#271]
I updated my HA docker image and now I can't use hass-cli. 
Listing devices doesn't work.
```
$ hass-cli -x device list
'result'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant_cli/cli.py", line 40, in run
    result = cli.main(standalone_mode=False)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant_cli/plugins/device.py", line 31, in listcmd
    devices = api.get_devices(ctx)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant_cli/remote.py", line 253, in get_devices
    'result'
KeyError: 'result'
```

I downloaded the source and added some debug print statements and it looks like the server is sending back this:
```
{'id': 1, 'type': 'result', 'success': False, 'error': {'code': 'unknown_command', 'message': 'Unknown command.'}}
```
The `hass-cli`  `info` and `event watch` commands still work. So I don't think it is a permissions problem.

Any ideas on what changed or if I broke something in my install?

**Comment by maxandersen** [comment]
what versions of hass-cli are you running and what version of homeassistant ?

I might very well be a change on server side as the devices api isn't exactly public api yet.

**Comment by DerekParks** [comment]
I tested with the dev branch `hass-cli, version 0.8.0.dev0` and `hass-cli, version 0.7.0`.

And my HA server is  `0.97.2`.

**Comment by maxandersen** [comment]
I've just tried this against a 0.98 of HA and it works for me. 

I also went and checked in HA code itself and the WS api messages for device list have remained unchanged for 1 year+ https://github.com/home-assistant/home-assistant/blame/4d08e73e3eb5db0391ca86488648b8acce95521d/homeassistant/components/config/device_registry.py#L12
